NftProject/Controllers/AuctionController.cs
using System.Net;
using System.Numerics;
using Contracts.Contracts.NFTMarketplace.ContractDefinition;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ActionConstraints;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using Nethereum.Contracts.Standards.ERC721;
using Nethereum.Web3;
using Newtonsoft.Json;
using NftContractHandler;
using NftProject.Data;
using NftProject.Models;
using NftProject.Models.ViewModels;

namespace NftProject.Controllers
{
    public class AuctionController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly TestExample _testExample;

        public AuctionController(ApplicationDbContext context, TestExample testExample)
        {
            _context = context;
            _testExample = testExample;
        }

        // GET: Auction
        public async Task<IActionResult> Index()
        {
            return View(await _context.AuctionInfo.ToListAsync());
        }

        // GET: Auction/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var auctionInfoModel = await _context.AuctionInfo
                .FirstOrDefaultAsync(m => m.Id == id);
            if (auctionInfoModel == null)
            {
                return NotFound();
            }

            return View(auctionInfoModel);
        }

        public async Task<IActionResult> SaleDetails(int? id)
        {
            if(id==null)
            {
                return NotFound();
            }
    
            var marketItems = (await _testExample.Service.FetchMyNFTsQueryAsync()).ReturnValue1;

            MarketItem marketItem = null;
            foreach (var item in marketItems)
            {
                //deserialize token uri
                if(item.TokenId != id)
                    continue;
                marketItem = item;
            }

            if (marketItem == null)
                return NotFound();
         
            string uri = await _testExample.Service.TokenURIQueryAsync(marketItem.TokenId);
             
            //reading metadata json from web 
            HttpWebRequest request = WebRequest.Create(uri) as HttpWebRequest;
            WebResponse resp = request.GetResponse();
            StreamReader reader = new StreamReader(resp.GetResponseStream());
            string jsonText = reader.ReadToEnd();
             
            NftViewItemModel res = new NftViewItemModel();
            res.NftMetadata = JsonConvert.DeserializeObject<NftMetadataModel>(jsonText);
            res.MarketData = marketItem;
         
            return View(res);
        }
        
        // GET: Auction/Create
        public async Task<IActionResult> Create(int? id)
        {
            
            if(id==null)
            {
                return NotFound();
            }
    
            var marketItems = (await _testExample.Service.FetchMyNFTsQueryAsync()).ReturnValue1;

            MarketItem marketItem = null;
            foreach (var item in marketItems)
            {
                //deserialize token uri
                if(item.TokenId != id)
                    continue;
                marketItem = item;
            }

            if (marketItem == null)
                return NotFound();
         
            string uri = await _testExample.Service.TokenURIQueryAsync(marketItem.TokenId);
             
            //reading metadata json from web 
            HttpWebRequest request = WebRequest.Create(uri) as HttpWebRequest;
            WebResponse resp = request.GetResponse();
            StreamReader reader = new StreamReader(resp.GetResponseStream());
            string jsonText = reader.ReadToEnd();
             
            NftViewItemModel res = new NftViewItemModel();
            res.NftMetadata = JsonConvert.DeserializeObject<NftMetadataModel>(jsonText);
            res.MarketData = marketItem;
            
            AuctionViewModel result = new AuctionViewModel();
            
            result.NftViewModel = res;

            result.AuctionInfo = new AuctionInfoModel();
            result.AuctionSale = new AuctionSaleModel();
            
            result.AuctionInfo.StartDate = DateTime.Today;
            result.AuctionInfo.TokenId = id.ToString();
            result.AuctionSale.TokenId = id.ToString();
            result.AuctionSale.Address = _testExample.CurrentUserAddress;

            return View(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AuctionViewModel auctionInfoModel)
        {

            if (ModelState.IsValid)
            {
                _context.Add(auctionInfoModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(auctionInfoModel); //change
        }
        
        // GET: Auction/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var auctionInfoModel = await _context.AuctionInfo.FindAsync(id);
            if (auctionInfoModel == null)
            {
                return NotFound();
            }
            return View(auctionInfoModel);
        }

        // POST: Auction/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,TokenId,MinimalBid,MinimalBidStep,StartDate,FinalDate")] AuctionInfoModel auctionInfoModel)
        {
            if (id != auctionInfoModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(auctionInfoModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AuctionInfoModelExists(auctionInfoModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(auctionInfoModel);
        }

        // GET: Auction/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var auctionInfoModel = await _context.AuctionInfo
                .FirstOrDefaultAsync(m => m.Id == id);
            if (auctionInfoModel == null)
            {
                return NotFound();
            }

            return View(auctionInfoModel);
        }

        // POST: Auction/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var auctionInfoModel = await _context.AuctionInfo.FindAsync(id);
            _context.AuctionInfo.Remove(auctionInfoModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AuctionInfoModelExists(int id)
        {
            return _context.AuctionInfo.Any(e => e.Id == id);
        }
        
        //get
        public async Task<IActionResult> MakeBid(string? id)
        {
            if(id==null)
            {
                return NotFound();
            }

            NftViewItemModel res = (await GetNft(id));

            AuctionViewModel model = new AuctionViewModel();
            model.NftViewModel = res;

            model.AuctionInfo = await _context.AuctionInfo.FirstOrDefaultAsync(m => m.TokenId == id)!;
            
            return View(model);
        }

        public async Task<IActionResult> MyBids()
        {
            string addr = _testExample.CurrentUserAddress;
            // check if bid are active!
            // by checkng the date

            
            //my bids token ids
            List<string> tokenIds = _context.AuctionSales
                .Where(m => m.Address.Equals(addr))
                .Select(m => m.TokenId).Distinct()
                .ToList();

            Console.WriteLine($"Count {tokenIds.Count}, {tokenIds[0]}");


            // which bids are active by my token id 
            List<AuctionInfoModel> myActiveBidsInfo = _context.AuctionInfo
                .Where(m => (m.FinalDate > DateTime.Today && tokenIds.Contains(m.TokenId)))
                .ToList();

            // Model of my 
            List<AuctionSaleModel> allActiveBids = _context.AuctionSales
                .Where(m => myActiveBidsInfo.
                                            Select(g => g.TokenId).
                                            ToList().Contains(m.TokenId))
                .ToList();

          //  List<AuctionSaleModel> myActiveBids = allActiveBids.Where(m => m.Address.Equals(addr)).ToList();
            
            // that is all my bids depending if final date has come or not  
            List<string> activeTokenIds = allActiveBids.Select(m => m.TokenId).Distinct().ToList();

            List<AuctionSaleModel> winningBids = new List<AuctionSaleModel>();
            foreach (var token in activeTokenIds)
            {
                winningBids.Add(allActiveBids.Where(m => m.TokenId.Equals(token)).OrderByDescending(m => m.Price).ToList().FirstOrDefault()!);
            }

            List<AuctionSaleModel> myWinningBids = winningBids.Where(m => m.Address.Equals(addr)).ToList();
            

NftProject/Controllers/NftController.cs
using System.Net;
using System.Numerics;
using Contracts.Contracts.NFTMarketplace.ContractDefinition;
using Ipfs.Http;
using Microsoft.AspNetCore.Mvc;
using Nethereum.Web3;
using Newtonsoft.Json;
using NftContractHandler;
using NftProject.Data;
using NftProject.Models;
using Org.BouncyCastle.Ocsp;

namespace NftProject.Controllers;

public class NftController : Controller
{
    private readonly IWebHostEnvironment _webHostEnvironment;
    private readonly IpfsClient _client;
    private readonly TestExample _testExample;
    private readonly ApplicationDbContext _dbContext;

    public NftController(IWebHostEnvironment webHostEnvironment, TestExample testExample, ApplicationDbContext dbContext)
    {
        _webHostEnvironment = webHostEnvironment;
        _client = new IpfsClient("https://ipfs.infura.io:5001/api/v0");
        _testExample = testExample;
        _dbContext = dbContext;
    }

    //GET
    public async Task<IActionResult> Index()
    {
        var marketItems = (await _testExample.Service.FetchMarketItemsQueryAsync()).ReturnValue1;

        List<NftViewItemModel> metaSet = new List<NftViewItemModel>(marketItems.Count);
        
        foreach (var item in marketItems)
        {
            NftViewItemModel tmp = new NftViewItemModel();
            tmp.NftMetadata = await ReadJsonFromWeb(item.TokenId);
            tmp.MarketData = item;

            //check if it is on auction
            AuctionInfoModel? dbResult = _dbContext.AuctionInfo.FirstOrDefault(m => m.TokenId.Equals(item.TokenId.ToString()));

            if (dbResult != null)
            {
                tmp.AuctionSale = true;
                string lastPrice = _dbContext.AuctionSales.OrderBy(m => m.Price).LastOrDefault(m => m.TokenId == dbResult.TokenId)?.Price
                                   ?? dbResult.startPrice;
                tmp.NftMetadata.Price = lastPrice;
            }

            metaSet.Add(tmp); 
        }
        
        
        return View(metaSet);
    }
    
    //Post
    //TODO: buy token || make it to redirect to details
    [HttpPost]
    public async Task<ActionResult> Index(string id, string price)
    {
        await _testExample.CreateMarketSale(BigInteger.Parse(id), BigInteger.Parse(price));
        return RedirectToAction(nameof(Index));
    }

    //GET
    public IActionResult Create()
    {
        return View();
    }
    
    //Post
    [HttpPost]
    [ValidateAntiForgeryToken]
     public async Task<IActionResult> Create([Bind("Name, Description, Price, FileUrl")] NftMetadataModel nftMetadata, IFormFile? fileUrl)
     {
            if (fileUrl != null)
                ModelState.Remove("FileUrl");
            
            
            if (ModelState.IsValid)
            {
                //add metadata to ipfs
                string url = await UploadToIpfs(nftMetadata, fileUrl);
                
                //create nft
                await _testExample.CreateToken(url, BigInteger.Parse(nftMetadata.Price));
                
                return RedirectToAction(nameof(Index));
            }
            
            return View(nftMetadata);
        }

     public async Task<IActionResult> Detail(string? id, string? nftaction)
     {

         if(id==null)
         {
             return NotFound();
         }

         string? price = Request.Query["Price"];
         if (price != null)
         {
             await _testExample.CreateMarketSale(BigInteger.Parse(id), BigInteger.Parse(price));
             return RedirectToAction(nameof(Index));
         }

         List<MarketItem> marketItems;
         
         if(nftaction!.Equals("MyNfts"))
             marketItems = (await _testExample.Service.FetchMyNFTsQueryAsync()).ReturnValue1;
         else 
             marketItems = (await _testExample.Service.FetchMarketItemsQueryAsync()).ReturnValue1;

         MarketItem? marketItem = null;
         foreach (var item in marketItems)
         {
             //deserialize token uri
             if(item.TokenId != BigInteger.Parse(id))
                 continue;
             marketItem = item;
         }

         if (marketItem == null)
             return NotFound();
         
         NftViewItemModel res = new NftViewItemModel();
         res.NftMetadata = await ReadJsonFromWeb(marketItem.TokenId);
         res.MarketData = marketItem;
         
         return View(res);
     }
     
     //Get
     public async Task<IActionResult> MyNfts()
     {
        
         var marketItems = (await _testExample.Service.FetchMyNFTsQueryAsync()).ReturnValue1;
         List<NftViewItemModel> metaSet = new List<NftViewItemModel>(marketItems.Count);
         
         foreach (var item in marketItems)
         {
             NftViewItemModel tmp = new NftViewItemModel();
             tmp.NftMetadata = await ReadJsonFromWeb(item.TokenId);
             tmp.MarketData = item;
             
             metaSet.Add(tmp); 
         }

         return View(metaSet);
     }
     
     
     //Post
     [HttpPost]
     public async Task<ActionResult> MyNfts(string id, string price)
     {
         await _testExample.ResellToken(BigInteger.Parse(id), BigInteger.Parse(price));
         return RedirectToAction(nameof(Index));
     }
     
     public async Task<IActionResult> NftListed()
     {
         var marketItems = (await _testExample.Service.FetchItemsListedQueryAsync()).ReturnValue1;
         List<NftViewItemModel> metaSet = new List<NftViewItemModel>(marketItems.Count);
         
         foreach (var item in marketItems)
         {
             NftViewItemModel tmp = new NftViewItemModel();
             tmp.NftMetadata = await ReadJsonFromWeb(item.TokenId);
             tmp.MarketData = item;
             
             metaSet.Add(tmp); 
         }

         return View(metaSet);
     }
     
     
     //TODO: WORK WITH WEB MAYBE TO OTHER CLASS
     public async Task<string> UploadToIpfs([Bind("Name, Description, Price, FileUrl")] NftMetadataModel nftMetadata, IFormFile? image)
     {
         var name = Path.Combine(_webHostEnvironment.WebRootPath + "\\Images", Path.GetFileName(image.FileName));
         FileStream f = new FileStream(name, FileMode.Create);
         await image.CopyToAsync(f);
         f.Close();
         
         string path = "Images\\" + image.FileName;
         

         var hash = await _client.FileSystem.AddFileAsync($"wwwroot/{path}");
         nftMetadata.FileUrl = $"https://ipfs.infura.io/ipfs/{hash.Id}";
         System.IO.File.Delete(name);
         
         //Store other 
         string metadata = JsonConvert.SerializeObject(nftMetadata);
         hash = await _client.FileSystem.AddTextAsync(metadata);
         
         string url = $"https://ipfs.infura.io/ipfs/{hash.Id}";
         
         return url;
     }
     
     private async Task<NftMetadataModel> ReadJsonFromWeb(BigInteger id)
     {
         string uri = await _testExample.Service.TokenURIQueryAsync(id);

         //reading metadata json from web 
         HttpWebRequest request = WebRequest.Create(uri) as HttpWebRequest;
         WebResponse resp = request.GetResponse();
         StreamReader reader = new StreamReader(resp.GetResponseStream());
         string jsonText = reader.ReadToEnd();

         NftMetadataModel NftMetadata = JsonConvert.DeserializeObject<NftMetadataModel>(jsonText);
         // NftMetadata.Price = Web3.Convert.FromWei(BigInteger.Parse(NftMetadata.Price)).ToString();
         return NftMetadata;
     }
}

NftProject/Views/Nft/Create.cshtml
@model NftMetadataModel

@{
    ViewBag.Title = "Create";
    Layout = "_Layout";
}

<h2>Create nft</h2>
<form asp-action="Create" method="post" enctype="multipart/form-data">
    
    <div class="p-4 rounded border">
        <div asp-validation-summary="ModelOnly" class="text-danger">

        </div>
        <h3>@ViewBag.message</h3>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Name"></label>
            </div>
            <div class="col-5">
                <input asp-for="Name" class="form-control" />
            </div>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Price"></label>
            </div>
            <div class="col-5">
                <input asp-for="Price" class="form-control" />
            </div>
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Description"></label>
            </div>
            <div class="col-5">
                <input asp-for="Description" class="form-control" />
            </div>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="FileUrl"></label>
            </div>
            <div class="col-5">
                <input asp-for="FileUrl" class="form-control" type="file" />
            </div>
            <span asp-validation-for="FileUrl" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-dark" value="Save" />
            <a asp-action="Index" class="btn btn-outline-dark">Back to List</a>
        </div>
    </div>
    
</form>

NftProject/Views/Nft/Detail.cshtml
@model NftViewItemModel
@{
    ViewBag.Title = "Detail";
    Layout = "_Layout";
}

<h2 class="text-dark">Nft Detail</h2>

@Html.Partial("_NftDetailsPartial", Model)

<div class="form-group">
    <a asp-action="Index" class="text-dark">Back to List</a>
</div>

@section Scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NftProject/Views/Nft/Index.cshtml
@using NftContractHandler
@model IEnumerable<NftViewItemModel>
@inject TestExample _testExample;

@{
    ViewData["Title"] = "Market";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br /><br />
<div class="row">
    <div class="col-6">
        <h2 class="text-dark">Nft for sale</h2>
    </div>
    <div class="col-6 text-right" style="text-align: end;">
        <a asp-action="Create" class="btn btn-dark"><i class="fas fa-plus"></i>&nbsp;Add New Nft</a>
    </div>

</div>
<br />
<br/><br/>
<div class="row">
    @foreach (var item in Model)
    {
        @Html.Partial("_NftPartial", item)
    }
</div>

@* <div class="col-4"> *@
@*     <div class="card mb-4"> *@
@*         <div class="card-header"> *@
@*             <h4 class="my-0 font-weight-normal"> *@
@*                 <label style="font-size: 23px;color: steelblue">@item.NftMetadata.Name</label> *@
@*             </h4> *@
@*         </div> *@
@*         <img src="@item.NftMetadata.FileUrl" alt="Card Image" class="card-img-top" style=""/> *@
@*         <div class="card-header"> *@
@*             <div class="d-flex justify-content-between align-items-center"> *@
@*                 <div class="btn-group"> *@
@*                     <label style="font-size: 20px;color: #a51313"><b>Price : @item.NftMetadata.Price</b></label> *@
@*                 </div> *@
@*                 <a asp-action="Detail" asp-route-id="@item.TokenId" class="btn btn-success pull-left btn-outline-info">Details</a> *@
@*                 $1$ @(await Html.RenderComponentAsync<BuyButton>(RenderMode.ServerPrerendered, new {TokenId = item.TokenId, Price = item.NftMetadata.Price})) #1# *@
@*                 $1$ <input type="submit" asp-controller="Nft" asp-action="Index" value="Buy" class="btn btn-success pull-right btn-outline-info"/> #1# *@
@*                 <form asp-action="Index" method="post" enctype="multipart/form-data"> *@
@*                     <button type="submit" asp-route-id="@item.TokenId" asp-route-price="@item.NftMetadata.Price" class="btn btn-success pull-right btn-outline-info">Get</button> *@
@*                 </form> *@
@*                 $1$ <BuyButton></BuyButton> #1# *@
@*                          *@
@*                 <component type="typeof(BuyButton)" render-mode="ServerPrerendered" param-TokenId="@item.TokenId.ToString()" param-Price="@item.NftMetadata.Price"/> *@
@*             </div> *@
@*         </div> *@
@*     </div> *@
@* </div> *@

NftProject/Views/Nft/MyNfts.cshtml
@using Nethereum.Metamask.Blazor
@model IEnumerable<NftViewItemModel>

@{
    ViewData["Title"] = "My Nfts";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br /><br />
<div class="row">
    <div class="col-6">
        <h2 class="text-dark">My nfts List</h2>
    </div>

</div>
<br />
<br/><br/>
<div class="row">
    @foreach (var item in Model)
    {
        @Html.Partial("_NftPartial", item)
    }
</div>

NftProject/Views/Nft/NftListed.cshtml
@model IEnumerable<NftViewItemModel>

@{
    ViewData["Title"] = "Listed";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br /><br />
<div class="row">
    <div class="col-6">
        <h2 class="text-dark">Nft for sale</h2>
    </div>
    <div class="col-6 text-right ">
        <a asp-action="Create" class="btn btn-dark"><i class="fas fa-plus"></i>&nbsp;Add New Nft</a>
    </div>

</div>
<br />
<br/><br/>
<div class="row">
    @foreach (var item in Model)
    {
        @Html.Partial("_NftPartial", item)
    }
</div>

NftProject/Views/Nft/SaleDetails.cshtml
@using Nethereum.Contracts.Standards.ERC721
@model NftViewItemModel
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2 class="text-info">Nft Detail</h2>
<form asp-action="Detail" method="post" enctype="multipart/form-data">
    <div class="p-4 rounded border row">
        <div asp-validation-summary="ModelOnly" class="text-danger">

        </div>
        <div class="col-8">
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="NftMetadata.Name"></label>
                </div>
                <div class="col-8">
                    <input type="hidden" asp-for="MarketData.TokenId" />
                    <input asp-for="NftMetadata.Name" readonly="readonly" class="form-control" />
                </div>
                <span asp-validation-for="NftMetadata.Name" class="text-danger"></span>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="NftMetadata.Price"></label>
                </div>
                <div class="col-8">
                    <input asp-for="NftMetadata.Price" readonly="readonly" class="form-control" />
                </div>
                <span asp-validation-for="NftMetadata.Price" class="text-danger"></span>
            </div>

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="NftMetadata.Description"></label>
                </div>
                <div class="col-8">
                    <input asp-for="NftMetadata.Description" readonly="readonly" class="form-control" />
                </div>
                <span asp-validation-for="NftMetadata.Description" class="text-danger"></span>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="MarketData.Owner"></label>
                </div>
                <div class="col-8">
                    <input asp-for="MarketData.Owner" readonly="readonly" class="form-control" />
                </div>
                <span asp-validation-for="MarketData.Owner" class="text-danger"></span>
            </div>
            
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="MarketData.Seller"></label>
                </div>
                <div class="col-8">
                    <input asp-for="MarketData.Seller" readonly="readonly" class="form-control" />
                </div>
                <span asp-validation-for="MarketData.Seller" class="text-danger"></span>
            </div>
            
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="MarketData.Sold"></label>
                </div>
                <div class="col-8">
                    <input asp-for="MarketData.Sold" readonly="readonly" class="form-control" />
                </div>
                <span asp-validation-for="MarketData.Sold" class="text-danger"></span>
            </div>
            
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="MarketData.TokenId"></label>
                </div>
                <div class="col-8">
                    <input asp-for="MarketData.TokenId" readonly="readonly" class="form-control" />
                </div>
                <span asp-validation-for="MarketData.TokenId" class="text-danger"></span>
            </div>
            

            <div class="form-group row">
                <div class="col-4">

                </div>
                <div class="col-8">

                </div>

            </div>
            <div class="form-group">
                <a asp-action="Index" class="btn btn-success">Back to List</a>
            </div>
        </div>
        <div class="col-1"></div>
        <div class="col-3">
            <img src="@Model.NftMetadata.FileUrl" width="100%" height="250px" style="border-radius: 5px;border: 1px solid #efefef" />
        </div>

    </div>
</form>

<form asp-action="MyNfts" method="post" enctype="multipart/form-data">
    @* change price *@
    <div class="form-group row">
        <div class="col-2">
            <label asp-for="NftMetadata.Price"></label>
        </div>
        <div class="col-5">
            <input asp-for="NftMetadata.Price" class="form-control" />
        </div>
        <span asp-validation-for="NftMetadata.Price" class="text-danger"></span>
    </div>

    <button type="submit" asp-route-id="@Model.MarketData.TokenId" asp-route-price="@Model.MarketData.Price" class="btn btn-success pull-right btn-outline-info">List Nft</button>
</form>

@* <a asp-area="" asp-controller="Auction" asp-action="Index" asp-route-id="@Model.MarketData.TokenId">Auction</a> *@



@section Scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}